import ButtonAppBar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import BackToTop from '@/components/button_to_top';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ButtonAppBar />
        <main>{children}</main>
        {/* <BackToTop /> */}
      </body>
    </html>
  )
}
