import Navbar from '@/components/Navbar'
import './globals.css'
import Provider from '@/components/Provider'

export const metadata = {
  title: 'Kitsu API',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
